apiVersion: v1
kind: Service
metadata:
  name: zwatcher-service
spec:
  selector:
    app: zwatcher
    tier: frontend
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
    nodePort: 31555
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zwatcher-deployment
  labels:
    app: zwatcher
    tier: frontend
spec:
  selector:
    matchLabels:
      app: zwatcher
      tier: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: zwatcher
        tier: frontend
    spec:
      containers:
      - name: zwatcher
        image: edwardstheo/zwatcher
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
        resources: 
                requests:
                        cpu: 400m                        
