apiVersion: v1
kind: Service
metadata:
  name: zwatcher-app
  labels:
    name: zwatcher-app
spec:
  type: NodePort
  ports:
    - port: 3036
      nodePort: 30036
      name: http
  selector:
    name: zwatcher-app
